id: I66D6D6B8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:47:42+00:00'
last_modified: '2022-06-16T05:00:15.765111+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21860
  title: རྒྱུན་སྤྱོད་བོད་རིགས་གཏམ་དཔེ་བསགས་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    0F3F:
      image_group_id: I4853
      title: ''
      total_pages: 661
      order: 1
      base_file: 0F3F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
